default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: 127.0.0.1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aula2_dev

test:
  <<: *default
  database: aula2_test

production:
  <<: *default
  database: aula2_prod